//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entity : DbContext
    {
        public Entity()
            : base("name=festivaldbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppUser> AppUser { get; set; }
        public virtual DbSet<Booth> Booth { get; set; }
        public virtual DbSet<BoothType> BoothType { get; set; }
        public virtual DbSet<EventItem> EventItem { get; set; }
        public virtual DbSet<Festival> Festival { get; set; }
        public virtual DbSet<Performer> Performer { get; set; }
        public virtual DbSet<Sale> Sale { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<Stage> Stage { get; set; }
        public virtual DbSet<Structure> Structure { get; set; }
        public virtual DbSet<TicketType> TicketType { get; set; }
        public virtual DbSet<Vendor> Vendor { get; set; }
    }
}
