//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1_1_test_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booth
    {
        public int Id { get; set; }
        public int FestivalId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string TypeCode { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public int W { get; set; }
        public int H { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string StageId { get; set; }
        public string Memo { get; set; }
    
        public virtual Festival Festival { get; set; }
        public virtual Stage Stage { get; set; }
        public virtual BoothType BoothType { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
