//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1_6_test_4
{
    using System;
    using System.Collections.Generic;
    
    public partial class seat
    {
        public int sno { get; set; }
        public int sname { get; set; }
        public int s_x { get; set; }
        public int s_y { get; set; }
        public int s_w { get; set; }
        public int s_h { get; set; }
    }
}
