//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1_5
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hotel()
        {
            this.reservation = new HashSet<reservation>();
        }
    
        public int hno { get; set; }
        public Nullable<int> ono { get; set; }
        public string hName { get; set; }
        public Nullable<int> ratno { get; set; }
        public string rno { get; set; }
        public Nullable<int> ano { get; set; }
        public Nullable<int> x { get; set; }
        public Nullable<int> y { get; set; }
        public string explanation { get; set; }
    
        public virtual address address { get; set; }
        public virtual owner owner { get; set; }
        public virtual rating rating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservation> reservation { get; set; }
    }
}
