//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1_1_test_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int Id { get; set; }
        public int FestivalId { get; set; }
        public string SaleTime { get; set; }
        public string Buyer { get; set; }
        public string Phone { get; set; }
        public int TicketTypeId { get; set; }
        public int Qty { get; set; }
        public string Pay { get; set; }
        public string Memo { get; set; }
        public string Status { get; set; }
        public System.DateTime SoldAt { get; set; }
    
        public virtual Festival Festival { get; set; }
        public virtual TicketType TicketType { get; set; }
    }
}
