//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1_6Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class outing
    {
        public int ono { get; set; }
        public int uno { get; set; }
        public int rno { get; set; }
        public System.TimeSpan out_time { get; set; }
        public Nullable<System.TimeSpan> in_time { get; set; }
        public System.DateTime out_day { get; set; }
    }
}
