//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1_6Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        public int rno { get; set; }
        public int uno { get; set; }
        public int sno { get; set; }
        public System.DateTime r_date { get; set; }
        public Nullable<System.DateTime> cafe_date { get; set; }
        public System.TimeSpan start_time { get; set; }
        public System.TimeSpan end_time { get; set; }
        public int r_time { get; set; }
        public int floor { get; set; }
        public int pay { get; set; }
    }
}
